name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Add EC2 to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H your_ec2_instance_ip >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          rsync -avz --exclude '.git*' ./ root@54.144.253.55:/var/www/html/ssldash/
          ssh root@54.144.253.55 'sudo systemctl restart nginx'
