name: Deploy to Ubuntu

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to server
        uses: appleboy/ssh-action@v3
        with:
          host: ${{ secrets.SERVER_IP }}  # Store server IP in a secret
          username: ${{ secrets.SERVER_USER }} # Store username in a secret
          key: ${{ secrets.SSH_KEY }}  # Store SSH key as a secret (not recommended)
          script: |
            cd /var/www/html/ssldash
            git pull origin main
            # Add additional deployment commands here
