name: Deploy to Ubuntu Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to server
        uses: LuisEnMarroquin/setup-ssh-action@v2.0.0  # Replace with the latest version (check for updates)
        with: 
            ORIGIN: ${{ secrets.SERVER_HOST }}
            SSHKEY: ${{ secrets.EC2_SSH_KEY }}
            NAME: production
            PORT: 22
      - run: cd /var/www/html/ssldash && sudo git pull origin main
