name: Deploy to Ubuntu Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to server
        uses: appleboy/ssh-action@v2  # Replace with the latest version (check for updates)
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ubuntu  # Adjust if you use a different username
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/html/ssldash  # Replace with the actual directory on your server
            sudo git pull origin main
            # Add your deployment commands here (e.g., npm install, yarn build, etc.)
