name: Deploy to AWS

on:
  push:
    branches: [ main ]  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Run the workflow on an Ubuntu runner

    steps:
      - uses: actions/checkout@v3  # Checkout your code from GitHub

      - name: Deploy to AWS
        uses: appleboy/ssh-action@v2  # Use SSH Action to deploy (latest version)
        with:
          host: 54.91.157.146  # Replace with your AWS instance IP
          username: root  # Since you added the key to root (not recommended)
          key: ${{ secrets.SSH_KEY }}  # Reference the uploaded SSH key secret
          port: 22  # Default SSH port
          script: |  # Deployment commands on the AWS instance
            sudo cp -r ./ /var/www/html/ssldash/  # Copy files (replace ./ with your source directory if different)
            sudo chown -R www-data:www-data /var/www/html/ssldash/  # Set ownership for Nginx
            sudo systemctl restart nginx  # Restart Nginx
