name: Run Command on EC2 Ubuntu 22

on:
  # Trigger the workflow on push events to the main branch
  push:
    branches: [ main ]

jobs:
  run-command:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure SSH access (store privateKey securely)
        env:
          # Replace with your actual private key (encrypted using GitHub Actions secrets)
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$PRIVATE_KEY" | tr -d '\r' > private_key && chmod 600 private_key

      - name: Run command on EC2 instance
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: ${{ secrets.SERVER_HOST }}  # Replace with your EC2 instance hostname or IP
          username: ${{ secrets.SERVER_USER }}  # Replace with the username on the EC2 instance (e.g., ubuntu)
          privateKey: ${{ path.resolve('./private_key') }}
          command: |  # Replace 'your_command' with the actual command to run
             git pull

