name: Deploy to Ubuntu Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}  # Replace with your server's hostname or IP address
          username: ubuntu  # Adjust if you use a different username
          key: ${{ secrets.EC2_SSH_KEY }}  # Reference the secret containing your private key
          script: |
            cd /var/www/html/ssldash  # Replace with the actual directory on your server
            sudo git pull origin main
            # Add your deployment commands here (e.g., npm install, yarn build, etc.)
